//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashDiscipline.Module.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SsisParameter", Namespace="http://schemas.datacontract.org/2004/07/CashDiscipline.ServiceLib.Types")]
    [System.SerializableAttribute()]
    public partial class SsisParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterName {
            get {
                return this.ParameterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterNameField, value) != true)) {
                    this.ParameterNameField = value;
                    this.RaisePropertyChanged("ParameterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterValue {
            get {
                return this.ParameterValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterValueField, value) != true)) {
                    this.ParameterValueField = value;
                    this.RaisePropertyChanged("ParameterValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntegrationPackageResult", Namespace="http://schemas.datacontract.org/2004/07/CashDiscipline.ServiceLib.Types")]
    [System.SerializableAttribute()]
    public partial class IntegrationPackageResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ExecutionIdentiferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CashDiscipline.Module.ServiceReference1.SsisOperationStatus OperationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CashDiscipline.Module.ServiceReference1.SsisMessage[] SsisMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ExecutionIdentifer {
            get {
                return this.ExecutionIdentiferField;
            }
            set {
                if ((this.ExecutionIdentiferField.Equals(value) != true)) {
                    this.ExecutionIdentiferField = value;
                    this.RaisePropertyChanged("ExecutionIdentifer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CashDiscipline.Module.ServiceReference1.SsisOperationStatus OperationStatus {
            get {
                return this.OperationStatusField;
            }
            set {
                if ((this.OperationStatusField.Equals(value) != true)) {
                    this.OperationStatusField = value;
                    this.RaisePropertyChanged("OperationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageName {
            get {
                return this.PackageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageNameField, value) != true)) {
                    this.PackageNameField = value;
                    this.RaisePropertyChanged("PackageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CashDiscipline.Module.ServiceReference1.SsisMessage[] SsisMessages {
            get {
                return this.SsisMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.SsisMessagesField, value) != true)) {
                    this.SsisMessagesField = value;
                    this.RaisePropertyChanged("SsisMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SsisOperationStatus", Namespace="http://schemas.datacontract.org/2004/07/CashDiscipline.ServiceLib.Types")]
    public enum SsisOperationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Running = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnexpectTerminated = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stopping = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completion = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SsisMessage", Namespace="http://schemas.datacontract.org/2004/07/CashDiscipline.ServiceLib.Types")]
    [System.SerializableAttribute()]
    public partial class SsisMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> MessageSourceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> MessageTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> MessageSourceType {
            get {
                return this.MessageSourceTypeField;
            }
            set {
                if ((this.MessageSourceTypeField.Equals(value) != true)) {
                    this.MessageSourceTypeField = value;
                    this.RaisePropertyChanged("MessageSourceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((this.MessageTypeField.Equals(value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ping", ReplyAction="http://tempuri.org/IService1/PingResponse")]
        string Ping(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ping", ReplyAction="http://tempuri.org/IService1/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExecuteSsisPackage", ReplyAction="http://tempuri.org/IService1/ExecuteSsisPackageResponse")]
        CashDiscipline.Module.ServiceReference1.IntegrationPackageResult ExecuteSsisPackage(string packageName, CashDiscipline.Module.ServiceReference1.SsisParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExecuteSsisPackage", ReplyAction="http://tempuri.org/IService1/ExecuteSsisPackageResponse")]
        System.Threading.Tasks.Task<CashDiscipline.Module.ServiceReference1.IntegrationPackageResult> ExecuteSsisPackageAsync(string packageName, CashDiscipline.Module.ServiceReference1.SsisParameter[] parameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CashDiscipline.Module.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CashDiscipline.Module.ServiceReference1.IService1>, CashDiscipline.Module.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ping(string value) {
            return base.Channel.Ping(value);
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(string value) {
            return base.Channel.PingAsync(value);
        }
        
        public CashDiscipline.Module.ServiceReference1.IntegrationPackageResult ExecuteSsisPackage(string packageName, CashDiscipline.Module.ServiceReference1.SsisParameter[] parameters) {
            return base.Channel.ExecuteSsisPackage(packageName, parameters);
        }
        
        public System.Threading.Tasks.Task<CashDiscipline.Module.ServiceReference1.IntegrationPackageResult> ExecuteSsisPackageAsync(string packageName, CashDiscipline.Module.ServiceReference1.SsisParameter[] parameters) {
            return base.Channel.ExecuteSsisPackageAsync(packageName, parameters);
        }
    }
}
