//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashDiscipline.Module.CashDisciplineServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SsisParameter", Namespace="http://schemas.datacontract.org/2004/07/CashDiscipline.ServiceLib.Types")]
    [System.SerializableAttribute()]
    public partial class SsisParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterName {
            get {
                return this.ParameterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterNameField, value) != true)) {
                    this.ParameterNameField = value;
                    this.RaisePropertyChanged("ParameterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterValue {
            get {
                return this.ParameterValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterValueField, value) != true)) {
                    this.ParameterValueField = value;
                    this.RaisePropertyChanged("ParameterValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntegrationPackageResult", Namespace="http://schemas.datacontract.org/2004/07/CashDiscipline.ServiceLib.Types")]
    [System.SerializableAttribute()]
    public partial class IntegrationPackageResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ExecutionIdentiferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReturnValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CashDiscipline.Module.CashDisciplineServiceReference.SsisMessage[] SsisMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ExecutionIdentifer {
            get {
                return this.ExecutionIdentiferField;
            }
            set {
                if ((this.ExecutionIdentiferField.Equals(value) != true)) {
                    this.ExecutionIdentiferField = value;
                    this.RaisePropertyChanged("ExecutionIdentifer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMessage {
            get {
                return this.ReturnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMessageField, value) != true)) {
                    this.ReturnMessageField = value;
                    this.RaisePropertyChanged("ReturnMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnValue {
            get {
                return this.ReturnValueField;
            }
            set {
                if ((this.ReturnValueField.Equals(value) != true)) {
                    this.ReturnValueField = value;
                    this.RaisePropertyChanged("ReturnValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CashDiscipline.Module.CashDisciplineServiceReference.SsisMessage[] SsisMessages {
            get {
                return this.SsisMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.SsisMessagesField, value) != true)) {
                    this.SsisMessagesField = value;
                    this.RaisePropertyChanged("SsisMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SsisMessage", Namespace="http://schemas.datacontract.org/2004/07/CashDiscipline.ServiceLib.Types")]
    [System.SerializableAttribute()]
    public partial class SsisMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> MessageSourceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> MessageTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> MessageSourceType {
            get {
                return this.MessageSourceTypeField;
            }
            set {
                if ((this.MessageSourceTypeField.Equals(value) != true)) {
                    this.MessageSourceTypeField = value;
                    this.RaisePropertyChanged("MessageSourceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((this.MessageTypeField.Equals(value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportBankStmtServiceParam", Namespace="http://schemas.datacontract.org/2004/07/CashDiscipline.ServiceLib.Types")]
    [System.SerializableAttribute()]
    public partial class ImportBankStmtServiceParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnzEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnzFilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CbaBosEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CbaBosFilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CbaOpEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CbaOpFilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WbcEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WbcFilePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AnzEnabled {
            get {
                return this.AnzEnabledField;
            }
            set {
                if ((this.AnzEnabledField.Equals(value) != true)) {
                    this.AnzEnabledField = value;
                    this.RaisePropertyChanged("AnzEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnzFilePath {
            get {
                return this.AnzFilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.AnzFilePathField, value) != true)) {
                    this.AnzFilePathField = value;
                    this.RaisePropertyChanged("AnzFilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CbaBosEnabled {
            get {
                return this.CbaBosEnabledField;
            }
            set {
                if ((this.CbaBosEnabledField.Equals(value) != true)) {
                    this.CbaBosEnabledField = value;
                    this.RaisePropertyChanged("CbaBosEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CbaBosFilePath {
            get {
                return this.CbaBosFilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.CbaBosFilePathField, value) != true)) {
                    this.CbaBosFilePathField = value;
                    this.RaisePropertyChanged("CbaBosFilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CbaOpEnabled {
            get {
                return this.CbaOpEnabledField;
            }
            set {
                if ((this.CbaOpEnabledField.Equals(value) != true)) {
                    this.CbaOpEnabledField = value;
                    this.RaisePropertyChanged("CbaOpEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CbaOpFilePath {
            get {
                return this.CbaOpFilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.CbaOpFilePathField, value) != true)) {
                    this.CbaOpFilePathField = value;
                    this.RaisePropertyChanged("CbaOpFilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WbcEnabled {
            get {
                return this.WbcEnabledField;
            }
            set {
                if ((this.WbcEnabledField.Equals(value) != true)) {
                    this.WbcEnabledField = value;
                    this.RaisePropertyChanged("WbcEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WbcFilePath {
            get {
                return this.WbcFilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.WbcFilePathField, value) != true)) {
                    this.WbcFilePathField = value;
                    this.RaisePropertyChanged("WbcFilePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CashDisciplineServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExecuteSsisPackage", ReplyAction="http://tempuri.org/IService1/ExecuteSsisPackageResponse")]
        CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult ExecuteSsisPackage(string packageName, CashDiscipline.Module.CashDisciplineServiceReference.SsisParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExecuteSsisPackage", ReplyAction="http://tempuri.org/IService1/ExecuteSsisPackageResponse")]
        System.Threading.Tasks.Task<CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult> ExecuteSsisPackageAsync(string packageName, CashDiscipline.Module.CashDisciplineServiceReference.SsisParameter[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ImportWbcForexRates", ReplyAction="http://tempuri.org/IService1/ImportWbcForexRatesResponse")]
        CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult ImportWbcForexRates(string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ImportWbcForexRates", ReplyAction="http://tempuri.org/IService1/ImportWbcForexRatesResponse")]
        System.Threading.Tasks.Task<CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult> ImportWbcForexRatesAsync(string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ImportBankStmt", ReplyAction="http://tempuri.org/IService1/ImportBankStmtResponse")]
        CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult ImportBankStmt(CashDiscipline.Module.CashDisciplineServiceReference.ImportBankStmtServiceParam paramObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ImportBankStmt", ReplyAction="http://tempuri.org/IService1/ImportBankStmtResponse")]
        System.Threading.Tasks.Task<CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult> ImportBankStmtAsync(CashDiscipline.Module.CashDisciplineServiceReference.ImportBankStmtServiceParam paramObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ImportApPmtDistn", ReplyAction="http://tempuri.org/IService1/ImportApPmtDistnResponse")]
        CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult ImportApPmtDistn(string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ImportApPmtDistn", ReplyAction="http://tempuri.org/IService1/ImportApPmtDistnResponse")]
        System.Threading.Tasks.Task<CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult> ImportApPmtDistnAsync(string filePath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CashDiscipline.Module.CashDisciplineServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CashDiscipline.Module.CashDisciplineServiceReference.IService1>, CashDiscipline.Module.CashDisciplineServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult ExecuteSsisPackage(string packageName, CashDiscipline.Module.CashDisciplineServiceReference.SsisParameter[] parameters) {
            return base.Channel.ExecuteSsisPackage(packageName, parameters);
        }
        
        public System.Threading.Tasks.Task<CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult> ExecuteSsisPackageAsync(string packageName, CashDiscipline.Module.CashDisciplineServiceReference.SsisParameter[] parameters) {
            return base.Channel.ExecuteSsisPackageAsync(packageName, parameters);
        }
        
        public CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult ImportWbcForexRates(string filePath) {
            return base.Channel.ImportWbcForexRates(filePath);
        }
        
        public System.Threading.Tasks.Task<CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult> ImportWbcForexRatesAsync(string filePath) {
            return base.Channel.ImportWbcForexRatesAsync(filePath);
        }
        
        public CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult ImportBankStmt(CashDiscipline.Module.CashDisciplineServiceReference.ImportBankStmtServiceParam paramObj) {
            return base.Channel.ImportBankStmt(paramObj);
        }
        
        public System.Threading.Tasks.Task<CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult> ImportBankStmtAsync(CashDiscipline.Module.CashDisciplineServiceReference.ImportBankStmtServiceParam paramObj) {
            return base.Channel.ImportBankStmtAsync(paramObj);
        }
        
        public CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult ImportApPmtDistn(string filePath) {
            return base.Channel.ImportApPmtDistn(filePath);
        }
        
        public System.Threading.Tasks.Task<CashDiscipline.Module.CashDisciplineServiceReference.IntegrationPackageResult> ImportApPmtDistnAsync(string filePath) {
            return base.Channel.ImportApPmtDistnAsync(filePath);
        }
    }
}
